
plugins {
    id 'com.android.application' version '8.2.2' apply true
}

android {
    namespace 'com.filtrofocus.app'
    compileSdk 34
    defaultConfig {
        applicationId "com.filtrofocus.app"
        minSdk 24
        targetSdk 34
        versionCode 17
        versionName "16.5-FINAL"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
