apply plugin: 'com.android.application'
android{namespace 'com.filtrofocus.app';compileSdk 34;defaultConfig{applicationId "com.filtrofocus.app";minSdk 24;targetSdk 34;versionCode 16;versionName "16.0-REAL"}compileOptions{sourceCompatibility JavaVersion.VERSION_17;targetCompatibility JavaVersion.VERSION_17}}
